services:
  - type: web
    name: seu-app-name
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: seu-database
          property: connectionString
      - key: REDIS_URL
        value: redis://seu-redis:6379